language: node_js
node_js:
  - "10"
os: linux
dist: xenial
arch: amd64
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn run test:ci
    - stage: release
      if: "(tag =~ /^v2/) AND (NOT (type IN (pull_request)))"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn run prepublishOnly
      deploy:
        provider: npm
        skip_cleanup: true
        email: npmjs@550.moe
        api_key:
          secure: npdpG0sNovdDNHNlnClzkHWkvMQqpAiSEukUVw3fVRYerENzdvI9rdz5KSrdztDsQADlyYeNHXNjnoAx81nSEZAA9XvA20W+Gaf114MIWfz80dcCb/qKwDAKaXM6SZYo1XZqEvqYRkKeXYAR4T6HIrMF8JZCwJZacR2MCoX2gywFheT3IB43JOkYrSDr/czdkwM3Ar3PY8QXz+JhBt/WuMS/fHZm4X5oAa6TCUH68jfPdzc4g6+IEnYagDbYmqDwnHuxmPqSGFijjynDrZgnM2KiQCZzVAufGccy+8xTgywrEShnKJF5xO/S+CG3Sn/jX53ib56HKZ8D/BNapR9I8MLtcsqzHn1wTCIF/4jJ26h5Ka3LPPaOfNwZboBbslOYIReS1wHoTBDogS37MaMo56S5f4It+lCARUuCQ9ToKp5ZRJatJRymtupa0TmaKycBDrhTyAMtxaNcFfnD49OD0FJTOl8vokOiy7fp74mi9A2KZdx0YO6QrmuVMf7uvBCXldKsfm0GF3LK0mCypa/57mEp4gIgEwfAKkz+icUows2feTa8Js2KcFVXiXYnOOFktr+TmntbeBHPNGyvzLuslpszi7J6lF/+02ODwCQOeuXIDxU4N8//cQFz9ZA9+lZ1nf1BL6yi27uQciNTg9QN+Ticcx4qU0uByLupfwTgbHk=
        on:
          tags: true
          repo: NervJS/taro-ui
          branch: master
    - stage: deploy
      if: "(branch = master) AND (NOT (type IN (pull_request)))"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn run build:doc
      after_script:
        - cd site
        - git init
        - echo 'taro-ui.aotu.io' > CNAME
        - git add .
        - git commit -m "Update Document"
        - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
    - GH_REF: github.com/NervJS/taro-ui.git
